apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
    owner: esobchak
  name: esobchak
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  ports:
    - protocol: TCP
      name: ftps
      port: 21
      targetPort: 21
    - protocol: TCP
      name: pasv-port
      port: 1025
      targetPort: 1025
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
    owner: esobchak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
        owner: esobchak
    spec:
      containers:
        - name: ftps
          image: ft_ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 1025