apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    owner: esobchak
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.49.2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
    owner: esobchak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        owner: esobchak
    spec:
      containers:
        - name: grafana
          image: ft_grafana
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
