# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    metallb.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: esobchak <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/05/03 15:58:22 by esobchak          #+#    #+#              #
#    Updated: 2021/05/03 15:59:16 by esobchak         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.104-192.168.99.104
