# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: esobchak <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/05/03 15:58:19 by esobchak          #+#    #+#              #
#    Updated: 2021/05/03 15:59:14 by esobchak         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name  : nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: nginx
    owner: esobchak
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    owner: esobchak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        owner: esobchak
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 443
