apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
    owner: esobchak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
        owner: esobchak
    spec:
      containers:
        - name: phpmyadmin
          image: ft_php
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
    owner: esobchak
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.49.2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


